INSERT INTO laquinzaine.type (idType, name) VALUES (1, 'IPA');
INSERT INTO laquinzaine.type (idType, name) VALUES (2, 'Pale Ale');
INSERT INTO laquinzaine.type (idType, name) VALUES (3, 'Lager');
INSERT INTO laquinzaine.type (idType, name) VALUES (4, 'Triple');
INSERT INTO laquinzaine.type (idType, name) VALUES (5, 'Stout');
INSERT INTO laquinzaine.type (idType, name) VALUES (6, 'Blanche');
INSERT INTO laquinzaine.type (idType, name) VALUES (7, 'Saison');
INSERT INTO laquinzaine.type (idType, name) VALUES (8, 'Sour');
INSERT INTO laquinzaine.type (idType, name) VALUES (9, 'Brune');
INSERT INTO laquinzaine.type (idType, name) VALUES (10, 'Fruitée');
